- Projets:
    - Network Learning:
        icon: mdi-school
        href: https://network-learning.lucipher-lab.fr
        description: Cours réseau interactifs

    - Whisper:
        icon: mdi-message-lock
        href: https://whisper.lucipher-lab.fr
        description: Secrets éphémères chiffrés

    - Prometheus:
        icon: mdi-folder-lock
        href: https://prometheus.lucipher-lab.fr
        description: Stockage & partage de fichiers

    - Relais:
        icon: mdi-shield-lock
        href: https://relais.lucipher-lab.fr
        description: Messagerie chiffrée de bout en bout
